### PR TITLE
Toootim/hebrew

### PR DESCRIPTION
**Pull request by seefood**
WHAT a mess!

ok, I have no idea what will happen when Gargron adds it to his master, but here goes for now:

toootim/master was reset to toootim/prod.

all my hebrew patches were squashed and cherry-picked on top on v1.2.2 (not master) at translate-hebrew. The only oddity is that they now contain translations to strings that are not yet in 1.2.2 and two dropped strings where dropped also from the Hebrew translation. I may actually rebase on master before I send it as a PR, but I want @yair to test it here first.

finally toootim/hebrew is toootim/master rebased on translate-hebrew. that's what this PR is.

enjoy.

### CODE REVIEW

**Comment by seefood** [comment]
nu? What do you think?

**Comment by yair** [comment]
Yes, a mess, and that's just the half of it. Two releases were made since this PR. So now we want to base everything on v1.3.1, of course, not v1.2.2.
I'm not really sure what the purpose of all these branches is right now since master was reset to prod, and prod is just v1.2.2 with local commits, but what I want is v1.3.1 with HebTrans and the server customization commits on top of it. So --
I'll branch off v1.3.1, pull everything on top of it, and see if it works. Then, we can give it a name, like master, or prod, or something.
Okay.
BTW, how are you doing all this? On the website? Using a local clone? With hub?

**Comment by seefood** [comment]
Well, 1.3X were not there yesterday when I made this, I'm fixing now and pushing.
the way I see it, you opened toootim/prod to be your active production branch, which is fine. I'll make my PRs to toootim/master which will be the staging, and once tested, you can merge, rebase, hard-reset or whatever to toootim/prod at your leisure.

at the moment, I have force-pushed (hate rebase!) a new translate-hebrew, now based on 1.3.1 (though I see they already committed a few more fixes onto it without tagging them...)

now I'm taking that and rebasing your local changes on top and force-pushing it as toootim/hebrew for you, but again I'm not sure it would really make sense to rebase that anymore, you may want to hard-reset it. we can decide later.

**Comment by seefood** [comment]
enjoy. I'm going to PR this to Gargron now.

**Comment by yair** [comment]
You might want to add the 6 missing user mailer files beforehand.

**Comment by seefood** [comment]
what mailer files? my PR is pretty much accepted to master.

**Comment by seefood** [comment]
NM, found them..

**Pull request closed without merging**
