### PR TITLE
created custom.scss for flexible column size

### PR DESCRIPTION
**Pull request by msappir**
Not sure this is the right place and not sure this is a complete enough SCSS file, so let's look into these questions before merging ;)

Based on this doc: https://github.com/tootsuite/documentation/blob/master/Running-Mastodon/Customizing.md

### CODE REVIEW

**Comment by eyalSci** [comment]
OK, we need to create this file in app/assets/stylesheets/custom.scss:
```
@import 'application';
   .drawer {
      width: 25vw;
            }
   .column {
      width: 25vw;
}
```
The problem it will will reduce the width of the columns & drawer to users who have a narrow screen, so they might difficult at reading long toots.
Instead, we could use this code:
```
@import 'application';
   .drawer {
      min-width: 330px;
      width: 25vw;
            }
   .column {
      min-width: 330px;
      width: 25vw;
}
```
So we just widen the columns, and won't narrow them. The downside here is that the users with narrow screen will stuck with the horizontal scroll-bar, and couldn't see the full site.
@adistav as the only known user on tooot.im with narrow screen, what do you think?

**Comment by elad661** [comment]
Copying what I said to Eyal in toootim:

1) min-width is necessary, otherwise the website will be completely unusable on narrow screens (the columns will be too narrow). If 330px is too much, 250px would also work as good minimum. anything lower than that makes things more and more unreadable.

2) There's already a mediaquery to automatically change the layout to single-column if the screen is too narrow, try re-sizing your screen and see. If anyone has a narrow screen that doesn't trigger this media query then perhaps the query should be tweaked.

Also, regarding Eyal's code in the comment above: I don't know scss, but if it's like regular CSS, it can be simplified to:
 ```scss
@import 'application';
   .column, .drawer {
      min-width: 330px;
      width: 25vw;
    }
```
(since the rules are exactly the same for both selectors, we don't need to duplicate them).

**Comment by msappir** [comment]
SCSS is a proper superset of CSS, so yes, that should work fine.

**Comment by eyalSci** [comment]
1. Yes, I agree. I try to minimize the screen and this was the result on this settings (without min-width) and the result is below.
2. I dunno, if a screen just a little narrow for full columns, I don't think we should force it to use only one column. But we could set a min-width to be just above the size which shrink to one column.
screenshot from 2017-04-26 17-23-20

**Comment by elad661** [comment]
Maybe we should change just the size of the `.column` and leave `.drawer` intact, right now it's narrower than the other 3 columns (300px) and I don't think it really needs to be widened. (try removing `.drawer` from the selector I posted in the previous comment and see how you like it).

**Comment by eyalSci** [comment]
It still bug me. No matter how to what we would set min-width, it will be to low when to layout change to single-column. We need to change it only on as a rule within the media queries when we have multiple-columns. I think it will also solve the problem of columns too narrow to be usable.

**Comment by msappir** [comment]
Have you guys checked how other people are implementing flexible columns? I know a few instances use them (anticapitalist.party, house targaryen...) and I think there's an issue and possibly a PR on the main repository asking to implement this as a standard feature...

**Comment by elad661** [comment]
@eyal6699 Of course, because it overrides the media-query since custom gets applied after all changes. We need to copy the media query and apply it in custom.scss too so it'll get priority.

**Comment by elad661** [comment]
@eyal6699 put this in your custom.scss:

```scss
@import 'application';
.column, .drawer {
     min-width: 330px;
     width: 25vw;
}
@media screen and (max-width: 1024px) {
  .column, .drawer {
        width: 100%;
        min-width: unset;
}
````

**Comment by elad661** [comment]
also: unset won't work on Internet Explorer (does work on Microsoft Edge), or really old versions of Firefox/Chrome, or the Android Browser, but I guess `min-width: 100%` would work on these? I'm not sure if you can specify percentage in min-width. and I'm not sure if we want to bother supporting these old browsers.

**Comment by eyalSci** [comment]
Working, it's great.
I think we should use min-width instead max-width in mediaqueries. It's more short and like you said, will cause less trouble.
If the min width of the screen is 1025, I don't think we should use min-width for column. It will be more than 250px in any case.
About the drawer, you right, but in my opinion it will be strange to leave it unchanged while the columns widen, I propose to widen it a little less.
So this is the result, what do you think?
```scss
@import 'application';

@media screen and (min-width: 1025px) {
     .drawer {width: 22vw;}
     .column {width: 26vw;}
}
```

**Comment by elad661** [comment]
This can work too, I guess? but 26vw is probably a bit too wide for the columns. I think the columns should stay `25vw` and the drawer should just be 300px.

And you still need `min-width: 250px` (or `min-width: 330px`) there because sometimes the screen is narrow but not narrow enough to trigger the mediaquery change.

**Comment by yair** [comment]
As I understand it, custom.scss is meant for site customization, to differentiate it from other sites in relatively small details (such as colors). There is already a lot of usability and general UI/UX stuff being done upstream that this might be in conflict with (or be made redundant by, or stuff). If these changes are worth while (and I certainly think they are), why not work with, and make them available to all of mastodon?

**Comment by elad661** [comment]
Because that's more work and upstream might decide to diverge and use a different solution. It's better to have this in our local instance as a temporary thing until upstream finds the solution that fits everyone.

(for example, it is possible that the columns are not wide upstream because upstream wanted space for custom columns as a future feature)

**Comment by elad661** [comment]
This was merged without taking our comments into account. And I guess that the "@import application" in @eyal6699's is required, and the fact that it's missing from the original code you merged in this PR is the reason tootim is broken at the moment.

Please revert this.

**Pull request merged**
