### PR TITLE
Add Hebrew interface translation.

### PR DESCRIPTION
**Pull request by seefood**
עברית שפה יפה

אימייל -> דואל
URL -> קישורית

עברית עדיין שפה יפה

איות וקצת תחביר, שיפור מגדר או שניים

Patch 3 (#3)

* תחביר ותרגום URI לקישורית

* עוד ענייני איות ותחביר

* תרגומים ואיות, מגדר ותות

* TYPO

### CODE REVIEW

**Comment by yair** [comment]
Missing language declarations in index.js etc. Needed according to https://github.com/tootsuite/documentation/blob/master/Contributing-to-Mastodon/Translating.md .

**Comment by seefood** [comment]
true. my changes depand on the ones by @mux2000. I'll rebase I guess.

**Comment by yair** [comment]
Okay. Thanks.

**Comment by seefood** [comment]
Enjoy

**Comment by seefood** [comment]
OK, this now includes michael's suggestions, I'll go over the docs and finish this PR. not ready for merging yet.

**Comment by yair** [comment]
Thank you.

**Comment by seefood** [comment]
ok, I think it's ready for merging.
there are new strings in master which I have not added here, I'll add them in a new branch.

**Comment by yair** [comment]
A+++ will squash, merge, rebase and pull into server tonight.

**Comment by yair** [comment]
Actually no... merge 1, merge 2, merge tootsuite/mastodon/master and cherrypick from tootim/mastodon/prod sounds better. Will it screw stuff up when when it's time to merge master into prod? Only one way to find out...

**Pull request merged**
